- id: "wilson"
  name: "Wilson Tam"
  profile_photo_src: "photos/trainer-4.jpg"
  specialty: "Fitness"
  body: "Certified Personal trainer by National Academy of Sports Medicine (NASM), Asian Academy for Sport and Fitness Professionals (AASFP) and PTA Global with more than 10 years of training experience with clients ranging all the way from age 5 to 75."
  bullets:
     - "Functional Movement Screen (FMS) Certified Exercise Professional"
     - "TRX & TRX Rip Certified Trainer"
     - "Kettlebell Certified Trainer"
     - "Gravity Training System Certified Trainer"
     - "Power Plate Certified Trainer"
  overview_bullets:
     - "Functional Movement Screen (FMS) Certified Exercise Professional"
     - "More than 10 years' experience"
- id: "calson"
  name: "Calson Leung"
  profile_photo_src: "photos/trainer-4.jpg"
  specialty: "Physio"
  body: "Calson is a registered physiotherapist specializes in musculoskeletal disorders and rehabilitative training with over 15 years of experience in private clinic and fitness industry."
  bullets:
     - "MSc. Healthcare (Physiotherapy)"
     - "BSc. Physiotherapy"
     - "Certified Strength & Conditioning Specialist (NSCA-CSCS)"
     - "Functional Movement Screen (FMS) Certified Exercise Professional"
     - "Movnat Certified Trainer (Level 1)"
  overview_bullets:
     - "MSc. Healthcare (Physiotherapy)"
     - "Movnat Certified Trainer (Level 1)"
- id: "elaine"
  name: "Elaine To"
  profile_photo_src: "photos/trainer-4.jpg"
  specialty: "Fitness"
  body: "Elaine has been a personal trainer for more than 12 years, with strong background in  martial arts and sports including Brazilian Jiu Jitsu, Muay Thai, Capoeira, boxing, rock climbing and bouldering etc. She has been the champion of her weight class in Muay Thai and Brazilian Jiu Jitsu from 2011 until 2014."
  bullets:
     - "Certified personal trainer by National Academy of Sports Medicine, Asian Academy for Sports & Fitness Professionals and PTA Global"
     - "Certified kettlebell trainer ( level 1)  by International Kettlebell and Fitness Federation"
     - "Certified TRX trainer"
     - "Certified Pre & Post natal Trainer by  Australian Graduate School of Health & Sports Science"
     - "Champion of 2014 Copa de Hong Kong Brazilian Jiu Jitsu female under 55kg (white belt division)"
     - "Champion of 2014 Epic Brazilian Jiu Jitsu female under 65kg (white belt division)"
     - "Champion of 2012 & 2011 The Ring muay thai competition"
     - "Participant of 2012 movement camp in Berlin, Germany"
  overview_bullets:
     - "Certified personal trainer by National Academy of Sports Medicine, Asian Academy for Sports & Fitness Professionals and PTA Global"
     - "More than 12 years' experience"
- id: "henry"
  name: "Henry Tong"
  profile_photo_src: "photos/trainer-4.jpg"
  specialty: "MMA"
  body: "Henry has devoted himself in Muay Thai & Martial Arts with more than 5 years of experience. He has had over 50 fight experiences including Brazilian Jiu Jitsu, Muay Thai, MMA,Sanshou,Boxing et and has been the champion of boxing, Sanshou and Muay thai in 2001, 2005, 2011, 2012"
  bullets:
     - "Certified Level one Muay Thai Coach Hong Kong Muay Thai Association"
     - "Certified SSF trainer by Asian Academy for Sports & Fitness Professionals"
     - "Second Place of 2001 Macau Open of Boxing 56kg division"
     - "Champion of 2001,2005,2011 Hong Kong Open for Sanshou 56kg division"
     - "Champion of Reunification Cup of Muaythai 2012 54kg divison"
     - "Winner of 17th & 19 thKF1 WORLD CHAMPIONSHIP 54kg division"
  overview_bullets:
     - "Certified Level one Muay Thai Coach Hong Kong Muay Thai Association"
     - "Over 5 years' experience"
- id: "cindy"
  name: "Cindy Lee"
  profile_photo_src: "photos/trainer-4.jpg"
  specialty: "Fitness"
  body: "<strong>\"Your unique Fitness & Life Coach\"</strong> <br><br> Cindy runs both 1 on 1 and group classes currently, leading clients in breaking through limitations, goal setting, coaching them to discover their life's ultimate purpose, while motivating client’s ability to master physical as well as mental health, and unleash their full power from the inside out."
  bullets:
     - "Certified Personal Trainer by National Academy of Sports Medicine"
     - "Certified NLP Trainer (ABNLP)"
     - "Certified NLP Master Coach (ABNLP)"
     - "Certified Master Hypnotist (American Board of Hypnotherapy)"
     - "Time Line TherapyTM Master Practitioner (Time Line Therapy Association)"
     - "MBA (University of Hull, UK)"
  overview_bullets:
     - "Certified Personal Trainer by National Academy of Sports Medicine"
     - "Certified NLP Trainer (ABNLP)"